#!/bin/sh
TOOLCHAIN_DIR=/home/dawn/t113_tina5.0_v1.2/prebuilt/rootfsbuilt/arm/toolchain-sunxi-glibc-gcc-830/toolchain
export STAGING_DIR="$TOOLCHAIN_DIR"
exec "$TOOLCHAIN_DIR/bin/arm-openwrt-linux-gnueabi-gcc" "$@"
